# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c687d970370a4762754e9e35dd5b18897597f83870c00dcfadb455468dbec87403730f617adbfc64b93bdc01d1470eb42a34ea6cc39ff83f9a4fd0179a0f1b49

test:
  secret_key_base: f921be721c6852dce59644a7c93b13cbfbc6b25ad8693a31a55281dee529be83f6f96be56c33bad9af0bb759e99da62c2744aa9745f327692c5c79c9ef3cbf1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
